### ISSUE TITLE
TypeError: Cannot read property 'prototype' of undefined with Jasmine 2.3

### ISSUE THREAD

**Issue by guncha** [cengage/promise-matchers#3]
Trying to do a require("promise-matchers") inside a beforeEach function fails with this error.

```
 Message:
    TypeError: Cannot read property 'prototype' of undefined
  Stack:
    TypeError: Cannot read property 'prototype' of undefined
      at Object.<anonymous> (node_modules/promise-matchers/src/promise-matchers.js:1:79)
      at Module._compile (module.js:460:26)
      at Object.Module._extensions..js (module.js:478:10)
      at Module.load (node_modules/coffee-script/lib/coffee-script/register.js:45:36)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Object.<anonymous> (spec/helpers/helpers.coffee:2:3)
      at runMicrotasksCallback (node.js:337:7)
      at process._tickCallback (node.js:355:11)
```

```
# grep \"version\" node_modules/*/package.json -R
...
node_modules/es6-promise/package.json:  "version": "3.0.2",
node_modules/jasmine/package.json:  "version": "2.3.2",
node_modules/promise-matchers/package.json:  "version": "0.9.6",
...
```

**Comment by deckar01** [comment]
I tried patching this into jasmine's new `addMatcher` API, but I think this library relies on some internal functionality of `Env` that has changed in jasmine 2.
https://gist.github.com/deckar01/6d2b339ec273212508c4

I did however make a quick drop-in replacement that will work for now.
https://gist.github.com/deckar01/e9ec4af655eaeb742781

I would still like to see `promise-matchers` updated for jasmine 2.
